# Generated by Django 5.0.6 on 2024-05-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0004_alter_produto_nome_alter_produto_preco_riscado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AddField(
            model_name='venda',
            name='desconto_aplicado',
            field=models.FloatField(blank=True, null=True, verbose_name='Desconto Aplicado'),
        ),
        migrations.AddField(
            model_name='venda',
            name='tem_desconto',
            field=models.BooleanField(default=False, verbose_name='Tem Desconto'),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Total'),
        ),
    ]
