# Generated by Django 5.0.6 on 2024-05-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0005_alter_venda_options_venda_desconto_aplicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='dia_da_semana',
            field=models.CharField(blank=True, choices=[('segunda-feira', 'Segunda-feira'), ('terca-feira', 'Terça-feira'), ('quarta-feira', 'Quarta-feira'), ('quinta-feira', 'Quinta-feira'), ('sexta-feira', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, null=True, verbose_name='Dia da Semana'),
        ),
    ]
