# Generated by Django 5.0.6 on 2024-05-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0006_venda_dia_da_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor da Venda'),
        ),
    ]
