# Generated by Django 5.0.6 on 2024-05-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0007_alter_venda_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='arquivado',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
    ]
