# Generated by Django 5.0.6 on 2024-05-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0008_venda_arquivado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='arquivado',
        ),
        migrations.AddField(
            model_name='produto',
            name='arquivado',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
    ]
