# Generated by Django 5.0.6 on 2024-05-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0009_remove_venda_arquivado_produto_arquivado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='dia_da_semana',
            field=models.CharField(blank=True, choices=[('Segunda-Feira', 'Segunda-feira'), ('Terca-Feira', 'Terça-feira'), ('Quarta-Feira', 'Quarta-feira'), ('Quinta-Feira', 'Quinta-feira'), ('Sexta-Feira', 'Sexta-feira'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20, null=True, verbose_name='Dia da Semana'),
        ),
    ]
