# Generated by Django 5.0.6 on 2024-05-19 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0011_alter_venda_dia_da_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='data_pedido',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='vendedor',
        ),
        migrations.AlterField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='granja.produto'),
        ),
    ]
