# Generated by Django 5.0.6 on 2024-05-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0012_remove_venda_data_pedido_remove_venda_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='dia_da_semana',
            field=models.CharField(blank=True, choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, null=True, verbose_name='Dia da Semana'),
        ),
    ]
