# Generated by Django 5.0.6 on 2024-05-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0013_alter_venda_dia_da_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='dia_da_semana',
            field=models.CharField(blank=True, choices=[('segunda', 'Segunda'), ('terca', 'Terça'), ('quarta', 'Quarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20, null=True, verbose_name='Dia da Semana'),
        ),
    ]
