# Generated by Django 5.0.6 on 2024-05-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0014_alter_venda_dia_da_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='meio_de_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartão_crédito', 'Cartão de Crédito'), ('cartão_débito', 'Cartão de Dédito')], default=0, max_length=20, verbose_name='Meio de Pagamento'),
        ),
    ]
