# Generated by Django 5.0.6 on 2024-05-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0015_venda_meio_de_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idade_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idade_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='interesses',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='mapa',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
