# Generated by Django 5.0.6 on 2024-05-22 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0016_alter_cliente_idade_max_alter_cliente_idade_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='granja.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='granja.desconto'),
        ),
    ]
