# Generated by Django 5.0.6 on 2024-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0017_alter_venda_cliente_alter_venda_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_entrega',
            field=models.DateField(auto_created=True),
        ),
    ]
