# Generated by Django 5.0.6 on 2024-05-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0020_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='meio_de_contato',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], default=0, max_length=20, verbose_name='Meio de Contado:'),
        ),
    ]
