# Generated by Django 5.0.6 on 2024-05-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0021_cliente_meio_de_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='meio_de_contato',
            field=models.CharField(choices=[(0, 'WhatsApp'), (1, 'Instagram')], default=0, max_length=20, verbose_name='Meio de Contado:'),
        ),
    ]
