# Generated by Django 5.0.6 on 2024-06-25 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0022_alter_cliente_meio_de_contato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='meio_de_contato',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], default=0, max_length=20, verbose_name='Meio de Contado:'),
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('vendedor', 'Vendedor'), ('comprador', 'Comprador')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarios', models.ManyToManyField(to='granja.appuser')),
            ],
        ),
    ]
