# Generated by Django 5.0.6 on 2024-06-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0024_empresa_endereco_empresa_nome_empresa_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.TextField(default='OI'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(default='OI', max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(default='OI', max_length=15),
        ),
    ]
