# Generated by Django 5.0.6 on 2024-06-25 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0026_alter_empresa_endereco_alter_empresa_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='arroba',
            field=models.CharField(default='granjaovosseujoao', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
