# Generated by Django 5.0.6 on 2024-08-11 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0027_empresa_arroba_alter_empresa_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Vendedor'), ('2', 'Comprador')], max_length=10),
        ),
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='granja.desconto'),
        ),
    ]
