# Generated by Django 5.0.6 on 2024-08-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0028_alter_appuser_user_type_alter_venda_desconto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default=None, upload_to='produtos/'),
        ),
    ]
